#!/bin/bash
# purpose: Search for a file and add it to the current "p" project.

VERSION=0.0.6
PROG=`basename $0`
ERR_EXIT=2

usage_top()   {
    echo "Usage: $PROG FILENAME_PART" >&2
}

short_usage() {
    usage_top
    echo "Try '$PROG --help' for more information." >&2
}

errout() {
    echo "$PROG: $*" >&2
    short_usage
    exit $ERR_EXIT
}

usage() {

    usage_top
    cat <<EOF_usage >&2
Search for a file and add it to the current "p" project.
Example: $PROG menu.h

  -h, --help                display this help text and exit
  -v, --version             display version information and exit
EOF_usage

}

do_short_usage() {
    short_usage
    exit $ERR_EXIT
}

version() {
   echo "$PROG $VERSION" >&2
}

OPTS=`getopt -o hv -l 'help,version' -- "$@"`
if [ $? != 0 ]; then
    short_usage
    exit $ERR_EXIT
fi

eval set -- "$OPTS"

while [ $# -gt 0 ]
do
    case "$1" in
               -h) do_short_usage
                   ;;
           --help) usage
                   exit
                   ;;
   -v | --version) version
                   exit
                   ;;
               --) shift
                   break
                   ;;
                *) errout "Invalid option: $1"
                   ;;
    esac
    shift
done

if [ "$#" -lt 1 ]; then
    do_short_usage
fi

cd /www
b=-1
while read a
do
    let b=b+1
    file[b]=$a
done < <(find . -iname "*$**" )

let i=0
until [ "$i" -gt "$b" ]
do
    echo "$i ${file[$i]}"
    let i=i+1
done

echo
f
echo -n "f "
read key index

f $key ${file[$index]}

