#!/usr/bin/perl

use 5.14.0;
use autodie;
use warnings;

use DateTime::Duration;
use DateTime::Format::Duration;

my $dur = DateTime::Duration->new();

my $d = DateTime::Format::Duration->new(
    pattern   => '%r',
    normalize => 1,
);

while (<>) {
    chomp;
    if ( $_ eq '' ) {
        say $d->format_duration($dur) . " SUBTOTAL\n";

        $dur = DateTime::Duration->new();
    }
    else {
        my $orig = $_;
        my @ja   = split ' ';
        $_ = $ja[0];
        my @hm = split ':';
        $_ = join ':', @hm;

        $dur = $dur + DateTime::Duration->new(
            hours   => $hm[0],
            minutes => $hm[1],
            seconds => $hm[2],
        );

        say "$orig";
    }
}

