#!/usr/bin/perl

# purpose: create subtotals from wlog time card output

use 5.14.0;
use autodie;
use warnings;

our $VERSION = '0.02';

my $hours = 0;
my $minutes = 0;
my $seconds = 0;

sub get_subtotal {
    $minutes += $seconds / 60;
    $seconds = $seconds % 60;
    $hours += $minutes / 60;
    $minutes = $minutes % 60;
    return sprintf("%3d:%02d:%02d",$hours,$minutes,$seconds);
}

sub clear_subtotal {
    $hours = $minutes = $seconds = 0;
}

sub add_times {
    my ($h,$m,$s) = @_;
    $hours += $h;
    $minutes += $m;
    $seconds += $s;
}

while (<>) {
    chomp;
    if ( $_ eq '' ) {
        print get_subtotal() . " SUBTOTAL\n\n";
        clear_subtotal();
    }
    else {
        my $orig = $_;
        my @ja   = split ' ';
        $_ = $ja[0];
        my @hm = split ':';
        $_ = join ':', @hm;

        add_times(@hm);

        print " $orig\n";
    }
}

