#!/usr/bin/bash
# purpose: locate file on local machine

VERSION=1.1.1

if [ "$1" == "-r" ]; then
    echo "Rebuilding index..." >&2
    find /cygdrive >~/data/full.cat
    shift
fi

grep -i "$*[^/]*$" ~/data/full.cat |less -FX

