#!/usr/bin/env perl
# Built from perl.t template
# purpose: renumber perl "debug 001" statements

#    Copyright (C) 2018  David M. Bradford
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your u_option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see https://www.gnu.org/licenses/gpl.txt
#
#    The author, David M. Bradford, can be contacted at:
#    davembradford@gmail.com


use strict;
use warnings FATAL => 'all';

BEGIN { $| = 1 }

use File::Basename;
use Getopt::Long;
use File::Temp qw/ tempfile /;
use File::Copy;

our $VERSION = '0.0.2';

my $PROG = basename($0);
my $ERR_EXIT = 2;

sub usage_top {
    warn "Usage: $PROG \n";
}

sub short_usage {
    usage_top();
    warn "Try '$PROG --help' for more information.\n";
}

sub errout {
    my $message = join( ' ', @_ );
    warn "$PROG: $message\n";
    short_usage();
    exit $ERR_EXIT;
}



sub usage {
    usage_top();
    warn <<EOF;
renumber perl "debug 001" statements
Example: $PROG pbug prog.pl

  -h, --help    display this help text and exit
  -v, --version display version information and exit

EOF
    return;
}

sub do_short_usage {
    short_usage();
    exit $ERR_EXIT;
}

sub version {
    warn "$PROG $VERSION\n";
    return;
}

my $h        = 0;
my $help     = 0;
my $version  = 0;


Getopt::Long::Configure ("bundling");

my %options = (
    "help"   => \$help,
    "version" => \$version,

);

# Explicitly add single letter version of each option to allow bundling
my ($key, $value);
my %temp = %options;
while (($key,$value) = each %temp) {
    my $letter = $key;
    $letter =~ s/(\w)\w*/$1/;
    $options{$letter} = $value;
}
# Fix-ups from previous routine
$options{h} = \$h;

GetOptions(%options) or errout("Error in command line arguments");

if    ($help)     { usage(); exit    }
elsif ($h)        { do_short_usage() }
elsif ($version)  { version(); exit  }


use warnings;
use strict;

use IO::File;

my ($infile) = @ARGV;

my $ifh = IO::File->new($infile, '<');
die if (!defined $ifh);

my ($fh, $outfile) = tempfile();

my $count = 1;
my $debug_on = 0;
while(<$ifh>) {
    chomp;

    if ( /END_DEBUG/ ) {
        $debug_on = 0;
    }

    if ( /debug \d\d\d/ ) {
        my $pcount = sprintf('%03d', $count++);
        s/debug \d\d\d/debug $pcount/;
    }
    elsif ( $debug_on && !/^\s*$/ ) {
        my $pcount = sprintf('%03d', $count++);
        print $fh qq{do_debug("$pcount");\n};
    }
    print $fh "$_\n";

    if ( /START_DEBUG/ ) {
        $debug_on = 1;
        print $fh <<'EOF';
{
	my $time = 0;
	sub do_debug {
		warn "debug $_[0]:" . (time() - $time);
		$time = time();
	}
}
EOF
    }
}
$ifh->close;
$fh->close;

copy($outfile, $infile) or die "Copy failed: $!";

$count--; # Started on 1, so decrement for correct count
warn "Updated $count debug statements\n";

