#!/usr/bin/perl
# purpose: print full path of a Perl module

use warnings;
use strict;

my $vim=0;
if ($ARGV[0] eq '-v') {
    $vim++;
    shift @ARGV;
}

for my $module ( @ARGV ) {
    my $package = $module;

    # From This::That to This/That.pm
    s/::/\//g, s/$/.pm/ for $module;

    if ( require $module ) {
        print $package . " => " . $INC{$module} . "\n";
        system("vim $INC{$module}") if $vim;
    }
}
